### ISSUE TITLE
Вопрос по организации кода

### ISSUE THREAD

**Issue by samelm** [yoksel/easy-markup#1]
Вот в этом http://yoksel.github.io/easy-markup/bem-rules/ разделе предлагается интересное решение для «разгрузки» селекторов с помощью нового БЭМ-блока `news__item news-item` Так вот, мне интересно, если использовать препроцессор и разбивать каждый БЭМ-блок на отдельные файлы, то нужно для этого блока создавать такой файл или всё же он используется как вспомогательный и не более?

**Comment by yoksel** [comment]
@samthe42 Если внутри блока находится достаточно сложная разметка, стили для неё логично будет вынести в отдельный файл, иначе можно рассматривать класс как вспомогательный и хранить стили в файле родительского блока. Я бы так сделала

**Comment by samelm** [comment]
@yoksel Спасибо, примерно так и предполагал!
