### ISSUE TITLE
Битые ссылки

### ISSUE THREAD

**Issue by kagulion** [yoksel/easy-markup#12]
1. Введение
• https://yoksel.github.io/easy-markup/accessibility/
• https://yoksel.github.io/first-steps/
• https://yoksel.github.io/bem-rules/
2. Первые шаги
• https://yoksel.github.io/bem-rules/
3. Как писать классы по БЭМ?
• https://yoksel.github.io/examples/
4. Тестируем всё
• https://yoksel.github.io/easy-markup/accessibility/
5. Поиск ошибок
• https://yoksel.github.io/drop-of-magic/#dusk
6. Доступность
• https://yoksel.github.io/first-steps/#tags

**Comment by yoksel** [comment]
Спасибо за репорт, сейчас всё должно исправиться
